---

# ####################################################################
#                             Task includes
# ####################################################################

- name: StatefulSet
  include_tasks: statefulset.yml

- name: Service
  include_task: service.yml
