---

# ####################################################################
#                             Task includes
# ####################################################################

- name: StatefulSet
  include_tasks: statefulset.yml
