---

# ####################################################################
#                             Task includes
# ####################################################################

- name: StatefulSet
  include_tasks: statefulset.yml

- name: Service
  include_tasks: service.yml
